import classnames from "classnames";

export const getAttributeClasses = ({
	autoplay,
	infinite,
	hasNavigation,
	hasPagination,
	stretchContentHeight,
	verticalAlign,
	timingFunction,
	autoHeight,
	centeredSlides,
	hasScrollbar,
	scrollbarMobileOnly,
	slideWidth,
	slidesPerView,
	paginationPosition,
	navigationPadding,
	navigationInset,
	hasOverflowVisible,
	effect,
	crossfade,
}) => {
	return classnames({
		autoplay: autoplay,
		infinite: infinite,
		"has-navigation": hasNavigation,
		"has-navigation-padding": navigationPadding,
		"has-navigation-inset": navigationInset,
		"has-pagination": hasPagination,
		"has-scrollbar": hasScrollbar,
		"has-scrollbar-mobile": scrollbarMobileOnly,
		[`has-pagination-position-${paginationPosition}`]: paginationPosition,
		"autoheight-slides": autoHeight,
		"centered-slides": centeredSlides,
		"stretch-content-height": stretchContentHeight,
		[`has-slide-align-${verticalAlign}`]: verticalAlign,
		[`has-timing-function-${timingFunction}`]: timingFunction,
		"has-slide-width": parseInt(slidesPerView) === 0 && slideWidth,
		"has-overflow-visible": hasOverflowVisible,
		[`has-effect-${effect}`]: effect,
		"has-crossfade": effect === "fade" && crossfade,
	});
};
